### ISSUE TITLE
Reproduce the result of totaltext

### ISSUE THREAD

**Issue by mxin262** [amazon-science/glass-text-spotting#3]
Hi, Thanks for your job. I trying to reproduce the result of totaltext. Can you provide the config of totaltext?

**Comment by tsiper** [comment]
Hi, we are working on releasing both the full evaluation code and evaluation configs for TotalText, ICDAR and TextOCR. I will update this issue once it's released, in about a week.

Thanks a lot for the interest in our work!

**Comment by tsiper** [comment]
Hi!

I'm happy to report that we've updated the config file for all the datasets, and the links are in the `README.md` file.

In addition, an evaluation script is found in `scripts/eval.py`, and an evaluation example will soon follow.
