### ISSUE TITLE
Demo for inferencing

### ISSUE THREAD

**Issue by JaegerStephan** [amazon-science/glass-text-spotting#6]
Hey!

Thank you very much for your great work and the corresponding repository.
Will there soon be a demo for inferencing available?

**Comment by tsiper** [comment]
Hi, thanks a lot for the interest in our work!

We are working on an inference demo based on Lab Collab, hopefully we'll get it ready by end of this week. I'll update this issue as soon as we get it ready

Thanks,
Shahar

**Comment by tsiper** [comment]
Hi!
I'm happy to update that we've just uploaded a lab collab demo, please check it out here:
https://colab.research.google.com/github/amazon-science/glass-text-spotting/blob/master/demo/glass_demo.ipynb
😄

**Comment by JaegerStephan** [comment]
Hi Shahar,

thank you for uploading a demo. I appreciate it a lot.
I'll give it a try in the new year.

All the bests,
Stephan
