### ISSUE TITLE
AttributeError: 'RotatedFastRCNNOutputs' object has no attribute 'predict_orientations'

### ISSUE THREAD

**Issue by deanofthewebb** [amazon-science/glass-text-spotting#7]
...glass/modeling/roi_heads/rotated_fast_rcnn.py  Line 356
        boxes = self.predict_boxes()
        scores = self.predict_probs()
        orientations = self.predict_orientations()

**Comment by tsiper** [comment]
Hi!

Thanks a lot for the interest in our package. The issue was fixed in the latest commit.
